using System;

namespace MobileWeb.Shared.CommonValues
{
    public class Enumeration
    {
        public enum ServiceId : int
        {
            COMMON_PAGE_ID = 1,

            CAT_FRITZYFRESHSPA_SERVICEID = 36,

            DOG_AND_PET_FLEA_AND_TICK_SERVICEID = 40,

            DOG_AND_PET_REMOISTURIZING_SERVICEID = 41,

            DOG_AND_PET_FRITZYFRESHSPA_SERVICEID = 43,

            DOG_AND_PET_CUTS_AND_TRIMS_SERVICEID = 44,

            CAT_CUTS_AND_TRIMS_SERVICEID = 45,

            CAT_FLEA_AND_TICK_SERVICEID = 49,

            MOBILEWEB_CAT_REMOISTURIZING_SERVICEID = 48,

            MOBILEWEB_CAT_DE_SHEDDING_SERVICEID = 75,

            DOG_AND_PET_DE_SHEDDING_SERVICEID = 77,

            CAT_TEETH_BRUSHING_SERVICEID = 79,

            DOG_AND_PET_TEETH_BRUSHING_SERVICEID = 81,

            DOG_AND_PET_BRUSHOUT_SERVICEID = 84,

            MOBILEWEB_CAT_BRUSHOUT_SERVICEID = 85,

            MOBILEWEB_CAT_MOTHERSDAY_SERVICEID = 86,

            DOG_AND_PET_ANAL_GLAND_EXPRESSION_SERVICEID = 86,

            DOG_AND_PET_BLUEBERRY_FACIAL_SERVICEID = 87,

            DOG_AND_PET_PAD_TREATMENT_SERVICEID = 88,

            DOG_AND_PET_HOLIDAYS_SERVICEID = 89,

            CAT_HOLIDAYS_SERVICEID = 90,

            DOG_AND_PET_VALENTINESDAY_SERVICEID = 91,

            CAT_VALENTINESDAY_SERVICEID = 92,

            DOG_AND_PET_SUPERBOWL_SERVICEID = 93,

            CAT_SUPERBOWL_SERVICEID = 94,

            DOG_AND_PET_MEDICATED_BATH_SERVICEID = 95,

            CAT_MEDICATED_BATH_SERVICEID = 96,

            CAT_BLUEBERRY_FACIAL_SERVICEID = 97,

            CAT_PAD_TREATMENT_SERVICEID = 98,

            CAT_SERVICE_ONE_SERVICEID = 99,

            CAT_SERVICE_TWO_SERVICEID = 100,

            CAT_ANAL_GLAND_EXPRESSION_SERVICEID = 101,

            DOG_AND_PET_SERVICE_ONE_SERVICEID = 102,

            DOG_AND_PET_SERVICE_TWO_SERVICEID = 103
        }
    }
}